package com.greatcan.moneysaver.configuration

import com.greatcan.moneysaver.R

enum class CategoryEnum(val title: Int, val resource: Int) {
    Bills(
            R.string.category_bills,
            R.drawable.icon_bills),
    Food(
            R.string.category_food,
            R.drawable.icon_food),
    Transportation(
            R.string.category_transportation,
            R.drawable.icon_transportation),
    Home(
            R.string.category_home,
            R.drawable.icon_home),
    Car(
            R.string.category_car,
            R.drawable.icon_car),
    Entertainment(
            R.string.category_entertainment,
            R.drawable.icon_entertainment),
    Shopping(
            R.string.category_shopping,
            R.drawable.icon_shopping),
    Clothing(
            R.string.category_clothing,
            R.drawable.icon_clothing),
    Insurance(
            R.string.category_insurance,
            R.drawable.icon_insurance),
    Tax(
            R.string.category_tax,
            R.drawable.icon_tax),
    Telephone(
            R.string.category_telephone,
            R.drawable.icon_telephone),
    Cigarette(
            R.string.category_cigarette,
            R.drawable.icon_cigarette),
    Health(
            R.string.category_health,
            R.drawable.icon_health),
    Sport(
            R.string.category_sport,
            R.drawable.icon_sport),
    Baby(
            R.string.category_baby,
            R.drawable.icon_baby),
    Pet(
            R.string.category_pet,
            R.drawable.icon_pet),
    Beauty(
            R.string.category_beauty,
            R.drawable.icon_beauty),
    Electronics(
            R.string.category_electronics,
            R.drawable.icon_electronics),
    Hamburger(
            R.string.category_hamburger,
            R.drawable.icon_hamburger),
    Wine(
            R.string.category_wine,
            R.drawable.icon_wine),
    Vegetables(
            R.string.category_vegetables,
            R.drawable.icon_vegetables),
    Snacks(
            R.string.category_snacks,
            R.drawable.icon_snacks),
    Gift(
            R.string.category_gift,
            R.drawable.icon_gift),
    Social(
            R.string.category_social,
            R.drawable.icon_social),
    Travel(
            R.string.category_travel,
            R.drawable.icon_travel),
    Education(
            R.string.category_education,
            R.drawable.icon_education),
    Fruits(
            R.string.category_fruits,
            R.drawable.icon_fruit),
    Book(
            R.string.category_book,
            R.drawable.icon_book),
    Office(
            R.string.category_office,
            R.drawable.icon_office),
    Others(
            R.string.category_others,
            R.drawable.icon_others)
}